version: '3.8'

services:
  postgres-db:
    image: postgres:16.1-alpine
    container_name: postgres
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  aiogram:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aiogram
    env_file:
      - .env
    depends_on:
      - postgres-db
